providers = ["java"]

[variables]
JAVA_VERSION = "17"

[phases.build]
cmds = [
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests=true"
]

[phases.start]
cmd = "java -Xmx512m -Dserver.port=$PORT -Dspring.profiles.active=default -jar target/MyTaskList-0.0.1-SNAPSHOT.jar"
