providers = ["java"]

[variables]
JAVA_VERSION = "17"

[phases.build]
cmds = [
  "chmod +x mvnw",
  "./mvnw clean package -DskipTests=true"
]

[phases.start]
cmd = "java -Xmx1024m -Dserver.port=$PORT -Dspring.profiles.active=railway -Djava.net.preferIPv4Stack=true -Dspring.main.lazy-initialization=false -jar target/MyTaskList-0.0.1-SNAPSHOT.jar"
